name: Auto Deploy

on:
  schedule:
  - cron: "0 2 * * 1-5"

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: EdricChan03/action-build-deploy-ghpages@v2.2.0
    env:
      github_token: d94c1f929886d2c25aa031ff0bfb9c6680c7914c
      gh_pages_token: ${{ secrets.GH_PAGES_TOKEN }}
      gh_pages_branch: 'master'
